### ISSUE TITLE
ssh-remote_access.py의 password 처리 문제

### ISSUE THREAD

**Issue by AI-chan-projects** [AI-chan-projects/super-app-tutorials#1]
```
def info_setting(explanations):
    constants = input(explanations)
    logger.info(f"Input received for {explanations.strip(':')}: {constants}")
    return constants

hostname = str(info_setting("hostname: "))
port = int(info_setting("port number: "))
username = str(info_setting("user name: "))
password = str(info_setting("password: "))
```

password 부분을 터미널에 사용자가 입력 할 때, 문자열이 그대로 노출되는 처리 문제가 있습니다.
해당 부분을 어떻게 해결하면 좋을까요?

**Comment by AI-chan-projects** [comment]
마크다운 형식으로 작성한 코드와 설명을 아래에 제공합니다.

```python
def info_setting(explanations):
    constants = input(explanations)
    logger.info(f"Input received for {explanations.strip(':')}: {constants}")
    return constants

hostname = str(info_setting("hostname: "))
port = int(info_setting("port number: "))
username = str(info_setting("user name: "))
password = str(info_setting("password: "))
```

`password` 부분을 터미널에 사용자가 입력할 때, 문자열이 그대로 노출되는 처리 문제가 있습니다.
해당 부분을 해결하려면 `input()` 대신 `getpass` 모듈의 `getpass()` 함수를 사용하여 비밀번호를 안전하게 입력받을 수 있습니다.

아래는 `getpass` 모듈을 사용한 수정된 코드를 보여줍니다:

```python
from getpass import getpass

def info_setting(explanations):
    constants = input(explanations)
    logger.info(f"Input received for {explanations.strip(':')}: {constants}")
    return constants

hostname = str(info_setting("hostname: "))
port = int(info_setting("port number: "))
username = str(info_setting("user name: "))

# `password`를 입력받을 때 `getpass()` 함수를 사용합니다.
password = getpass("password: ")
```

`getpass()` 함수는 터미널에서 비밀번호를 입력받을 때 사용자에게 입력된 비밀번호를 숨겨주며, 입력된 비밀번호를 안전하게 다룰 수 있도록 도와줍니다.

**Comment by AI-chan-projects** [comment]
Git에서 이슈와 관련된 브랜치를 생성하고, 변경 사항을 병합하는 방법을 단계별로 안내하겠습니다.

1. **이슈 브랜치 생성**: 이슈와 관련된 작업을 위해 새로운 브랜치를 생성합니다. 브랜치 이름은 이슈 번호를 포함하여 의미 있는 이름으로 지정합니다. 예를 들어, 이슈 번호가 `#1`이고 이슈의 내용이 `password 처리 문제`와 관련되어 있다면 다음과 같이 브랜치를 생성합니다:

    ```bash
    git checkout -b issue-1-password-fix
    ```

    이 명령은 `issue-1-password-fix`라는 이름의 새로운 브랜치를 생성하고 현재 작업 브랜치로 전환합니다.

2. **코드 수정**: 생성한 브랜치에서 이슈에 대한 수정을 진행합니다. 이 경우, 비밀번호 입력을 `input()` 대신 `getpass()`를 사용하여 처리하는 등의 변경 작업을 수행합니다.

3. **커밋**: 변경된 파일을 스테이징하고 커밋합니다. 먼저 변경된 파일을 스테이징하고:

    ```bash
    git add ssh-remote_access.py
    ```

    그런 다음, 변경 내용을 커밋 메시지와 함께 커밋합니다:

    ```bash
    git commit -m "이슈 #1: 비밀번호 처리 문제 해결 - getpass 사용"
    ```

4. **브랜치 푸시**: 작업이 완료되면, 원격 저장소에 브랜치를 푸시합니다:

    ```bash
    git push origin issue-1-password-fix
    ```

5. **풀 리퀘스트(Pull Request) 생성**: 원격 저장소에서 해당 브랜치에 대해 풀 리퀘스트를 생성하여 변경 사항을 리뷰하고 병합합니다. 풀 리퀘스트는 브랜치를 주 저장소의 메인 브랜치(예: `main`)로 병합하도록 요청하는 절차입니다.

6. **코드 리뷰 및 병합**: 풀 리퀘스트가 생성되면 팀원들과 함께 코드 리뷰를 진행합니다. 리뷰가 완료되면 메인 브랜치로 병합할 수 있습니다.

위 절차를 따르면 이슈와 관련된 브랜치를 생성하고 변경 사항을 병합할 수 있습니다. 병합 후에는 관련 브랜치를 정리해주는 것도 좋습니다.

**Comment by skwwnl** [comment]
추후에 Password를 단방향 hash로 변환한 값을 DB( RDBMS, NoSQL )에 저장 후 비교하는 Code Line 필요.
